import tkinter as tk
root = tk.Tk()
root.geometry('800x800')
root.title("Grrr!")
label = tk.Label(root, text='Grrr!')
label.pack()
image = tk.PhotoImage(file='fight.gif')
label = tk.Label(root, image=image)
label.pack()
entry = tk.Entry(root)
entry.pack()
button = tk.Button(root, text="WOW! Nice try")
button.pack()
root.mainloop()
